### ISSUE TITLE
Renaming alert doesn't change it

### ISSUE THREAD

**Issue by CheekyScorp** [appoptics/terraform-provider-appoptics#44]
Renaming an alert reports back as successful but doesn't actually change the resource.
e.g. 
```
module.********: Modifying... (ID: 1234)
  name: "name-NEW" => "name"
module.******: Modifications complete after 9s (ID: 1234)
```

**Comment by pcn** [comment]
You discovered what I discovered around the same time. Check out https://github.com/appoptics/terraform-provider-appoptics/pull/45/commits/e6decca5a87f03b23d75c8f2ab099d33f1450dbd#diff-67f991c94bb36946aa55d5c4d54ec3a7R403.

**Comment by solarchad** [comment]
This should be fixed from @pcn's latest release: https://github.com/appoptics/terraform-provider-appoptics/releases/tag/0.4.0-beta.1 - can you give it a shot and let us know?
