### ISSUE TITLE
Upgrade to be compatible with Terraform 0.12.x syntax

### ISSUE THREAD

**Issue by solarchad** [appoptics/terraform-provider-appoptics#7]
- See: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html
- Before we do this, make sure there's a version released for <= 0.11.x TF compatible versions

**Comment by n0rig** [comment]
What's the status of this, guys?

**Comment by solarchad** [comment]
@n0rig and @sandnabba: there's a [new beta release](https://github.com/appoptics/terraform-provider-appoptics/releases/tag/0.4.0-beta.1) which _should_ work with Terraform versions 0.12 and 0.13. Can you give it a shot and report back if it's not working for you?

**Comment by sandnabba** [comment]
@n0rig @solarchad Yeah, we've been using that for a few weeks without any issues (only to setup alerts). But so far, all good! :) +1
